name: Diagnose CDN (basic smoke test)
on:
  workflow_dispatch:
  push:
    branches:
      - 'ci/diagnose-cdn'

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create basic log
        run: |
          mkdir -p logs
          echo "diagnose-smoke: $(date -u +%Y-%m-%dT%H:%M:%SZ)" > logs/diagnose.txt
          echo "ok" > logs/status.txt
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: diagnose-smoke-logs
          path: logs


