name: Diagnose CDN (basic smoke test)
on:
  workflow_dispatch:
  push:
    branches:
      - 'ci/diagnose-cdn'

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run full diagnostic script
        run: |
          chmod +x scripts/diagnose-cdn.sh
          scripts/diagnose-cdn.sh "${{ inputs.cdn || 'https://updates.threadsbooster.jp' }}" "${{ inputs.bucket || 'container-browser-updates' }}"
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: diagnose-logs
          path: logs


