name: Build & Publish Windows (nsis-web)

on:
  push:
    branches: [ main ]

jobs:
  build_publish_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build app (renderer + main)
        run: npm run build

      - name: Install native app dependencies
        run: npx electron-builder install-app-deps

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build (electron-builder, no publish)
        env:
          CI: true
        run: npx electron-builder --win --x64 --publish=never

      - name: List dist output
        run: |
          echo "--- dist tree ---"
          if (Test-Path dist) { Get-ChildItem -Recurse dist | Select-Object FullName,Length | Format-Table -AutoSize } else { echo "dist not found" }

      - name: Upload artifacts to S3 (aws cli)
        run: |
          $ErrorActionPreference = 'Stop'
          echo "Uploading built artifacts to s3://container-browser-updates/"
          if (Test-Path dist) {
            # upload common artifact types produced by electron-builder
            aws s3 cp --recursive dist s3://container-browser-updates/ --exclude "*" --include "*.exe" --include "*.7z" --include "*.nsis" --include "*.yml" --no-progress
          }
          # also upload top-level latest.yml if present
          if (Test-Path .\latest.yml) { aws s3 cp .\latest.yml s3://container-browser-updates/latest.yml --no-progress }

      - name: Show latest.yml if present (from S3)
        run: |
          echo "--- latest.yml from S3 ---"
          aws s3 cp s3://container-browser-updates/latest.yml ./latest.yml || echo "latest.yml not found on S3"
          if (Test-Path .\latest.yml) { Get-Content .\latest.yml -Raw } else { echo "latest.yml not found on S3" }

      - name: Invalidate CloudFront cache for latest.yml (optional)
        run: |
          if ($env:CLOUDFRONT_DISTRIBUTION_ID) {
            aws cloudfront create-invalidation --distribution-id $env:CLOUDFRONT_DISTRIBUTION_ID --paths "/latest.yml"
          } else {
            echo "CLOUDFRONT_DISTRIBUTION_ID not set; skip invalidation"
          }


