name: Build & Publish Windows (nsis-web)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build_publish_windows:
    runs-on: windows-latest
    env:
      CSC_LINK: ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Cache electron caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-electron-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-electron-

      - name: Install dependencies
        run: npm ci

      - name: Build app (renderer + main)
        run: npm run build

      - name: Install native app dependencies
        run: npx electron-builder install-app-deps

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Detect version change (robust)
        id: version
        shell: pwsh
        run: |
          # Ensure non-fatal behaviour inside this step
          $ErrorActionPreference = 'SilentlyContinue'

          $pkg = 'package.json'
          $prev = $null
          $curr = $null
          $changed = $true

          try {
            # Read current package version
            $currJson = Get-Content -LiteralPath $pkg -Raw
            $curr = (ConvertFrom-Json $currJson).version

            $before = '${{ github.event.before }}'
            Write-Host "DEBUG: before=[$before]"

            if ($before -and $before.Trim().Length -gt 0) {
              # ensure logs dir exists for debug artifacts
              New-Item -ItemType Directory -Force -Path logs | Out-Null

              # fetch and inspect previous package.json (stderr discarded)
              git fetch --no-tags --no-recurse-submodules --depth=1 origin $before 2>$null | Out-Null
              $file = git show "$before:$pkg" 2>$null
              if ($LASTEXITCODE -eq 0 -and $file -and ($file -is [string]) -and $file.Trim().Length -gt 0) {
                try { $prev = (ConvertFrom-Json $file).version } catch { $prev = $null }
              } else {
                Write-Host 'DEBUG: git show returned empty or non-string content for package.json'
              }
            } else {
              Write-Host 'DEBUG: before is empty; treating as changed=true'
            }

            if ($prev -and $curr) { $changed = ($curr -ne $prev) } else { $changed = $true }
          } catch {
            Write-Host ('DEBUG: unexpected error in detect step: {0}' -f $_.Exception.Message)
            $changed = $true
          } finally {
            # Always emit outputs and exit cleanly
            "prev=$prev" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
            "curr=$curr" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
            "changed=$changed" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
            exit 0
          }

      - name: Publish nsis-web via script
        if: steps.version.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        shell: pwsh
        env:
          WIN_CSC_LINK: ''
          CSC_LINK: ''
          CSC_KEY_PASSWORD: ''
        run: |
          powershell -NoProfile -ExecutionPolicy Bypass -File scripts\update-release.ps1 `
            container-browser-updates `
            E1Q66ASB5AODYF `
            https://updates.threadsbooster.jp

      - name: CDN health (HEAD=200 / Range=206)
        if: steps.version.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        shell: pwsh
        run: |
          powershell -NoProfile -ExecutionPolicy Bypass -File scripts\check-cdn-health.ps1 -CDN 'https://updates.threadsbooster.jp'



