name: Build & Publish Windows (nsis-web)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build_publish_windows:
    runs-on: windows-latest
    env:
      CSC_LINK: ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Cache electron caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-electron-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-electron-

      - name: Install dependencies
        run: npm ci

      - name: Build app (renderer + main)
        run: npm run build

      - name: Install native app dependencies
        run: npx electron-builder install-app-deps

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Detect version change
        id: version
        shell: pwsh
        run: |
          $before='${{ github.event.before }}'
          if (-not $before) { "changed=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8; exit 0 }
          git fetch --no-tags --depth=2 origin $before
          $old = git show $before:package.json | ConvertFrom-Json
          $new = Get-Content package.json -Raw | ConvertFrom-Json
          if ($old.version -ne $new.version) { "changed=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8 } else { "changed=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8 }

      - name: Publish nsis-web via script
        if: steps.version.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        shell: pwsh
        run: |
          powershell -NoProfile -ExecutionPolicy Bypass -File scripts\update-release.ps1 `
            container-browser-updates `
            E1Q66ASB5AODYF `
            https://updates.threadsbooster.jp

      - name: CDN health (HEAD=200 / Range=206)
        if: steps.version.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        shell: pwsh
        run: |
          powershell -NoProfile -ExecutionPolicy Bypass -File scripts\check-cdn-health.ps1 -CDN 'https://updates.threadsbooster.jp'



