name: Release Web Installer
on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*"
jobs:
  build-publish:
    runs-on: windows-latest
    env:
      AWS_REGION: ap-northeast-1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - name: Install deps
        run: npm ci
      - name: Build & Publish artifacts
        shell: bash
        run: |
          chmod +x scripts/release-web.sh
          scripts/release-web.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


